lansguage: node_js
node_js:
- '6'
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
before_install:
- chmod 600 ~/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_74cc3739aa67_key -iv $encrypted_74cc3739aa67_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- echo "build success"
