lansguage: node_js
node_js:
- '6'
branchs:
  only:
  - master
install:
- npm install
- cd blog && npm install
script:
- npm run build
- cd ../ && npm run build
cache:
  directories:
    - node_modules
    - blog/node_modules
addons:
  ssh_known_hosts:
  - 65.49.207.115
before_install:
- openssl aes-256-cbc -K $encrypted_74cc3739aa67_key -iv $encrypted_74cc3739aa67_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- echo "build success"
- ssh travis@$host -p $host_port -o StrictHostKeyChecking=no 'bash ~/shell/build_lord.sh'
